# Use an official Python runtime as a parent image
FROM python:3.11.8-slim

# Install git
RUN apt-get update && apt-get install -y git \
    build-essential \
    libclblast-dev \
    libopenblas-dev

ARG clone_arg
ARG commit

RUN git clone https://github.com/LostRuins/koboldcpp.git $clone_arg \
    && cd koboldcpp \
    && if [ -n "$commit" ]; then git checkout $commit; fi \
    && pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt \
    && make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set the working directory
WORKDIR /koboldcpp

# Make port 80 available to the world outside this container
EXPOSE 80

# Use koboldcpp.py as the entrypoint when the container launches
CMD ["python", "koboldcpp.py"]