# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /koboldcpp

# Install git
RUN apt-get update && apt-get install -y git \
    build-essential \
    libclblast-dev \
    libopenblas-dev \
    && git clone https://github.com/LostRuins/koboldcpp.git --branch v1.43 ./ \
    && pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt \
    && make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1 \
    && apt-get clean s&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Make port 80 available to the world outside this container
EXPOSE 80

# Use koboldcpp.py as the entrypoint when the container launches
CMD ["python", "koboldcpp.py"]